#!/usr/bin/env node
// The reader's own switch for the constructs this grammar cannot make loud.
//
// A few constructs read as body text in a quarter or more of the bundled themes, and
// `corpus/prose-reading-ledger.txt` rules each one: the family that would cure it either lies about
// what it names, or costs a neighbouring construct its declared distinction. A TextMate grammar cannot
// reach past that — it emits a static name and a theme decides — and this extension ships no runtime to
// decide for anybody. What remains honest hands the READER the switch, with the measurement beside it.
//
// GENERATED, NEVER WRITTEN. The rows derive from the ledger and from the contrast reading, so a scope
// that stops reading as prose leaves the recipe the day it does, and one that starts joins it. A
// hand-kept list in a README goes stale silently, which is the failure a reader meets as a lie.
//
// A COLOUR OUTLIVES A THEME SWITCH; A FONT STYLE DOES NOT. Every recommendation carries `fontStyle`
// alone, so each theme keeps its own palette and the construct gains a mark a reader can find. A reader
// wanting colour gives each theme its own block, the way the README's own example shows.
//
//   node tools/reading-recipe.js            print the block
//   node tools/reading-recipe.js --write    weld it into README.md

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { loadThemes } = require('./theme-model.js');
const { reads, stacks, rulings, BAR } = require('./contrast-witness.js');

const ROOT = path.resolve(__dirname, '..');
const MARK = '<!-- reading-recipe -->';

// A mark a reader can find, chosen for what the construct MEANS rather than for variety: a raised run
// wants raising, a lowered run wants lowering, and a name a wiki resolves wants underlining.
const MARKS = {
  'markup.superscript': 'bold',
  'markup.subscript': 'bold',
  'variable.name.mvv-display': 'underline'
};
const FALLBACK = 'underline';

/**
 * Every ruled scope that still reads as prose, with how many themes leave it there and why it stands.
 *
 * @returns {Promise<{key: string, scope: string, themes: number, why: string, settings: {fontStyle: string}}[]>}
 */
async function recipe() {
  const themes = loadThemes().filter((t) => t.defaults && t.defaults.foreground);
  const corpus = await stacks();
  const ruled = rulings();
  const rows = [];
  for (const { scope, reason } of ruled) {
    const carrying = corpus.filter((e) => e.stack.some((sc) => sc === `${scope}.tiddlywiki5`
      || sc.startsWith(`${scope}.`)));
    if (!carrying.length) continue;
    let quiet = 0;
    for (const theme of themes) {
      if (carrying.some((e) => { const r = reads(e.stack, theme, theme); return r.prose; })) quiet += 1;
    }
    if (quiet <= BAR) continue;
    // The ledger's reason runs long for a reader of the ledger; a recipe wants its first clause.
    const why = reason.split(/\.\s|\. /)[0].replace(/\s+/g, ' ').trim();
    rows.push({ key: scope, scope: `${scope}.tiddlywiki5`, themes: quiet, why, settings: { fontStyle: MARKS[scope] || FALLBACK } });
  }
  return rows.sort((a, b) => b.themes - a.themes);
}

/** The markdown block, welded into the README between its marks. */
function render(rows, themeCount) {
  const lines = [MARK, '', '### Constructs your theme leaves quiet', ''];
  lines.push('Three readings sit outside what a scope name can reach: the family that would make each one'
    + ' loud either names the construct something it is not, or costs a neighbouring construct a'
    + ' distinction a reader needs. Measured across the bundled themes:', '');
  lines.push('| construct | reads as prose in | why it stands |');
  lines.push('| --- | --- | --- |');
  for (const r of rows) lines.push(`| \`${r.scope}\` | ${r.themes} of ${themeCount} themes | ${r.why} |`);
  lines.push('', 'A `fontStyle` rule gives each one a mark your own theme keeps its colours under:', '');
  lines.push('```json');
  lines.push('"editor.tokenColorCustomizations": {');
  lines.push('  "textMateRules": [');
  lines.push(rows.map((r) => `    { "scope": "${r.scope}", "settings": { "fontStyle": "${r.settings.fontStyle}" } }`).join(',\n'));
  lines.push('  ]');
  lines.push('}');
  lines.push('```');
  lines.push('', `Generated by \`npm run reading-recipe\` from \`corpus/prose-reading-ledger.txt\`, so a`
    + ` construct that stops reading quiet leaves this table the day it does.`);
  lines.push(MARK);
  return lines.join('\n');
}

module.exports = { recipe, render, MARK };

if (require.main !== module) return;

(async () => {
  const themes = loadThemes().filter((t) => t.defaults && t.defaults.foreground);
  const rows = await recipe();
  const block = render(rows, themes.length);
  if (!process.argv.includes('--write')) {
    console.log(block);
    process.exitCode = 0;
    return;
  }
  const file = path.join(ROOT, 'README.md');
  const readme = fs.readFileSync(file, 'utf8');
  const first = readme.indexOf(MARK);
  const last = readme.lastIndexOf(MARK);
  if (first < 0) {
    console.error(`  README.md carries no ${MARK} block to weld into`);
    process.exitCode = 2;
    return;
  }
  const next = readme.slice(0, last + MARK.length);
  fs.writeFileSync(file, readme.slice(0, first) + block + readme.slice(last + MARK.length));
  console.log(`reading-recipe  ${rows.length} construct(s) welded into README.md`);
  process.exitCode = 0;
})();
